# Generated by Django 2.1.5 on 2019-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('teamName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('github_username', models.CharField(max_length=150)),
                ('project_repo_name', models.CharField(max_length=150)),
                ('teamSize', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('userDetail1', models.CharField(max_length=150)),
                ('userDetail2', models.CharField(blank=True, max_length=150, null=True)),
                ('userDetail3', models.CharField(blank=True, max_length=150, null=True)),
                ('fieldProject', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
